[pytest]
testpaths = test
addopts =
    --html=reports/testing/index.html
    --junitxml=reports/junit.xml
    --cov=flaskapp
    --cov-report=html:reports/coverage
    --cov-report=xml:reports/coverage.xml
